### ISSUE TITLE
Breaks if tsconfig.json extends from a config defined in node_modules

### ISSUE THREAD

**Issue by tconroy** [joonhocho/tscpaths#16]
My `tsconfig.json` contains an `extends` property, which targets a config that is a node_module dependency:
```json
{
  "extends": "@org/ts-config",
  ...
}
```

however this breaks tscpaths:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '<redacted>/@org/ts-config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.exports.loadConfig (<redacted>/node_modules/tscpaths/cjs/util.js:16:12)
    at Object.exports.loadConfig (<redacted>/node_modules/tscpaths/cjs/util.js:28:38)
    at Object.<anonymous> (<redacted>/node_modules/tscpaths/cjs/index.js:37:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

```

it seems `loadConfig()` in `utils` is not able to correctly resolve non-relative/non-absolute `extends` clauses.

**Comment by garretteklof** [comment]
Was there a workaround for this?

**Comment by tconroy** [comment]
Hi @garretteklof -- unfortunately I was unable to find a workaround. We migrated away from tscpaths as a result.
